name: "OWASP ZAP DAST"

on:
  workflow_run:
    workflows: ["CodeQL SAST Scan"]
    types: [completed]

jobs:
  zap_scan:
    name: Run OWASP ZAP against deployed app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Spin up the app (e.g., Docker Compose)
    - name: Start application & dependencies
      run: |
        docker-compose up -d
        # wait for service to be healthy
        timeout 60 bash -c \
          'until curl -s http://localhost:3000; do sleep 5; done'

    # 2. Run ZAP baseline scan
    - name: Run OWASP ZAP baseline scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: "http://localhost:3000"
        rules_file_name: zap-rules.txt   # optional custom rule suppressions
        fail_on_warn: true
        cmd_options: -r zap-report.html

    # 3. Upload report
    - name: Upload ZAP report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
