name: Bandit → Deploy → DAST

on:
  push:
    branches: [ 'master', 'main' ]
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:

jobs:
  bandit:
    name: Bandit SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd  # :contentReference[oaicite:3]{index=3}
        with:
          exit_zero: true
          config_file: bandit.yaml    # point to tuned config :contentReference[oaicite:4]{index=4}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-and-dast:
    name: Deploy Flask & DAST
    runs-on: ubuntu-latest
    needs: bandit                                # wait for Bandit success
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask app
        run: |
          nohup flask --app app run --host 0.0.0.0 --port 5000 &
          sleep 10

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0   # ZAP Baseline DAST :contentReference[oaicite:8]{index=8}
        with:
          target: 'http://localhost:5000'       # your Flask endpoint :contentReference[oaicite:9]{index=9}
          token: ${{ secrets.GITHUB_TOKEN }}
