name: Deploy & DAST

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  deploy:
    name: Build & Deploy Flask
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start Flask in background
        run: |
          nohup python app.py &       # assumes your app listens on 0.0.0.0:5000
          sleep 10                     # give it a moment to spin up

  dast:
    name: DAST (OWASP ZAP Baseline)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:5000'
          format: 'sarif'
          output: 'zap-baseline.sarif'

      - name: Upload ZAP SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-baseline.sarif
        if: always()
